---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certificate-updater-sa
  namespace: certificate-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certificate-updater-rb
  namespace: certificate-updater
subjects:
  - kind: ServiceAccount
    name: certificate-updater-sa
    namespace: certificate-updater
roleRef:
  kind: ClusterRole
  name: modify-node
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modify-node
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodemaintenances
    verbs:
      - get
      - list
      - modify
      - patch